//
// Created by Miha on 28/07/2023.
//

#ifndef CRASHPAD_CRASHUPLOADTHREADCALLBACKINTERFACE_H
#define CRASHPAD_CRASHUPLOADTHREADCALLBACKINTERFACE_H

class CrashUploadThreadCallbackInterface {

};

#endif  // CRASHPAD_CRASHUPLOADTHREADCALLBACKINTERFACE_H
