macro(dependency_root_path DEPENDENCY DEPENDENCY_ROOT)
    string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UPPER)
    set(${DEPENDENCY_ROOT} ${${DEPENDENCY}_PACKAGE_FOLDER_${CMAKE_BUILD_TYPE_UPPER}})
endmacro()
